import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, Bookmark, Building2, Check, ChevronRight, Cpu, Database, GraduationCap, Layers3, Network, ShieldCheck, Sparkles, Workflow, type LucideIcon } from 'lucide-react';
import { domains } from '../data/domains';
import { conceptPath, href, industryPath, type ConceptSummary, type IndustrySummary } from '../lib/catalog';
import type { Progress } from '../lib/state';
export const domainIcons:LucideIcon[]=[Network,ShieldCheck,Activity,Database,Cpu,Sparkles];
export const pad=(n:number)=>String(n).padStart(2,'0');
export const domainLabel=(id:number)=>domains[id]?.short||'Advanced collection';
export const domainColor=(id:number)=>domains[id]?.color||'teal';
export function Brand({small=false}:{small?:boolean}){return <a href={href()} className="brand" aria-label="AI Architecture home"><span className="brand-symbol"><Layers3 size={23}/></span>{!small&&<span>AI Architecture<small>THE DESIGN REFERENCE</small></span>}</a>;}
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>;}
export function PageIntro({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <header className="page-intro"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{description}</p>{children}</header>;}
export function SectionHeading({label,title,text,link}:{label:string;title:string;text?:string;link?:{path:string;text:string}}){return <div className="section-heading"><div><div className="section-label">{label}</div><h2>{title}</h2>{text&&<p>{text}</p>}</div>{link&&<a className="text-link" href={href(link.path)}>{link.text}<ArrowUpRight size={16}/></a>}</div>;}
export function ConceptCard({concept,progress,onSave,compact=false}:{concept:ConceptSummary;progress:Progress;onSave:(id:number)=>void;compact?:boolean}){const Icon=domainIcons[concept.category]||Sparkles;return <article className={`concept-card color-${domainColor(concept.category)} ${compact?'compact':''}`}><div className="card-top"><span className="category-tag"><Icon size={14}/>{domainLabel(concept.category)}</span><button className={`icon-button save-button ${progress.saved.includes(concept.id)?'is-saved':''}`} onClick={()=>onSave(concept.id)} aria-label={`${progress.saved.includes(concept.id)?'Unsave':'Save'} ${concept.title}`} aria-pressed={progress.saved.includes(concept.id)}><Bookmark size={16} fill={progress.saved.includes(concept.id)?'currentColor':'none'}/></button></div><a href={href(conceptPath(concept))} className="card-main"><span className="concept-number">{concept.id>100?'EXTENSION':'CONCEPT'} {pad(concept.id)}</span><h3>{concept.title}</h3><p>{concept.summary}</p><div className="card-bottom"><span>{progress.completed.includes(concept.id)?<><Check size={14}/>Completed</>:<><Workflow size={14}/>{concept.diagrams||1} architecture {concept.diagrams===1?'diagram':'diagrams'}</>}</span><ArrowUpRight size={18}/></div></a></article>;}
export function MiniNetwork({variant=0}:{variant?:number}){return <svg className={`mini-network mini-${variant%3}`} viewBox="0 0 260 88" role="img" aria-label="Agents coordinate through a shared workflow"><g className="network-edges" fill="none"><path d="M30 44H98M130 44H165Q175 44 175 20H217M165 44H217M165 44Q175 44 175 68H217"/><path className="network-return" d="M225 76H114V58"/></g><rect x="10" y="31" width="43" height="26" rx="6"/><rect className="central" x="89" y="25" width="57" height="38" rx="8"/><rect x="210" y="7" width="39" height="23" rx="5"/><rect x="210" y="33" width="39" height="23" rx="5"/><rect x="210" y="59" width="39" height="23" rx="5"/><circle cx="31" cy="44" r="3"/><circle cx="118" cy="44" r="5"/><path d="m222 18 4 4 7-7m-11 30 4 4 7-7m-11 30 4 4 7-7" fill="none"/></svg>;}
export function IndustryCard({industry,index=0}:{industry:IndustrySummary;index?:number}){return <a className={`industry-card color-${['teal','blue','violet','amber'][index%4]}`} href={href(industryPath(industry))}><div className="card-top"><span className="industry-sector"><Building2 size={16}/>{industry.name}</span><ArrowUpRight size={17}/></div><MiniNetwork variant={index}/><h3>{industry.title}</h3><p>{industry.summary}</p><div className="card-bottom"><span>{industry.agents} specialist agents</span><span>{industry.diagrams} diagrams</span></div></a>;}
export function EmptyState({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="empty-state"><BookOpen size={28}/><h2>{title}</h2><p>{text}</p>{action}</div>;}
export function Breadcrumb({items}:{items:{label:string;path?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><a href={href()}>Home</a>{items.map((item,i)=><span key={i}><ChevronRight size={12}/>{item.path?<a href={href(item.path)}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</span>)}</nav>;}
export function DownloadLink(){return <a className="button secondary" href={href('curriculum.md')} download="AI_Agent_Architecture_Curriculum.md"><ArrowDownToLine size={16}/>Download curriculum</a>;}
export function ArrowButton({path,children,secondary=false}:{path:string;children:React.ReactNode;secondary?:boolean}){return <a className={`button ${secondary?'secondary':'primary'}`} href={href(path)}>{children}<ArrowRight size={17}/></a>;}
export function StudyBadge(){return <span className="study-badge"><GraduationCap size={14}/>Architecture reference</span>;}
