import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, Circle, ExternalLink, List, ShieldCheck } from 'lucide-react';
import type { Reference } from '../lib/content-types';
import { usePersistent } from '../lib/state';
export function TableOfContents({items}:{items:{id:string;label:string}[]}){const [active,setActive]=useState(items[0]?.id);useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setActive(entry.target.id);},{rootMargin:'-90px 0px -60% 0px'});items.forEach(i=>{const el=document.getElementById(i.id);if(el)observer.observe(el);});return()=>observer.disconnect();},[items]);return <aside className="page-toc"><div><List size={15}/>ON THIS PAGE</div><nav aria-label="On this page">{items.map(item=><a key={item.id} className={active===item.id?'active':''} href={`#${item.id}`}>{item.label}</a>)}</nav><a className="back-top" href="#page-top">Back to top<ArrowUpRight size={13}/></a></aside>;}
export function ReferenceSection({id,kicker,title,children}:{id:string;kicker?:string;title:string;children:React.ReactNode}){return <section className="reference-section" id={id}>{kicker&&<div className="section-label">{kicker}</div>}<h2><a href={`#${id}`}>{title}<span aria-hidden="true">#</span></a></h2>{children}</section>;}
export function RuntimeFlow({steps}:{steps:{title:string;description:string}[]}){return <ol className="runtime-flow">{steps.map((step,i)=><li key={i}><span className="flow-index">{String(i+1).padStart(2,'0')}</span><div><h3>{step.title}</h3><p>{step.description}</p></div></li>)}</ol>;}
export function TradeoffTable({items}:{items:{decision:string;benefit:string;cost:string}[]}){return <div className="table-scroll"><table className="reference-table"><thead><tr><th>Design decision</th><th>What improves</th><th>What you take on</th></tr></thead><tbody>{items.map(item=><tr key={item.decision}><th scope="row">{item.decision}</th><td>{item.benefit}</td><td>{item.cost}</td></tr>)}</tbody></table></div>;}
export function FailureCards({items}:{items:{scenario:string;detection:string;recovery:string}[]}){return <div className="failure-cards">{items.map((item,i)=><article key={i}><div className="failure-title"><ShieldCheck size={19}/><h3>{item.scenario}</h3></div><dl><dt>Detect</dt><dd>{item.detection}</dd><dt>Recover</dt><dd>{item.recovery}</dd></dl></article>)}</div>;}
export function ArchitectureChecklist({items,conceptId}:{items:string[];conceptId:number}){
  const [checked,setChecked]=usePersistent<number[]>(`architecture-checklist-${conceptId}`,[],v=>Array.isArray(v)?v.filter((n):n is number=>Number.isInteger(n)&&n>=0&&n<items.length):[]);
  return <div className="architecture-checklist"><div className="checklist-head"><span><Check size={16}/>{checked.length} of {items.length} reviewed</span><button onClick={()=>setChecked([])} disabled={!checked.length}>Reset checklist</button></div><div className="checklist-track"><span style={{width:`${items.length?checked.length/items.length*100:0}%`}}/></div>{items.map((item,i)=><label key={i} className={checked.includes(i)?'checked':''}><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(p=>p.includes(i)?p.filter(n=>n!==i):[...p,i])}/><span className="checkbox-visual">{checked.includes(i)?<Check size={12}/>:<Circle size={12}/>}</span><span>{item}</span></label>)}<p className="small-note">A design review aid. Checked items are saved in this browser and do not certify a production system.</p></div>;
}
export function References({items}:{items:Reference[]}){return <ul className="references-list">{items.map((ref,i)=><li key={i}><a href={ref.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span>{ref.title}<ExternalLink size={14}/></a></li>)}</ul>;}
export function ResourceLoading({title,error,retry}:{title:string;error:string;retry:()=>void}){return <div className="resource-loading"><div className="section-label">ARCHITECTURE REFERENCE</div><h1>{title}</h1>{error?<div role="alert"><p>{error}</p><button className="button primary" onClick={retry}>Try again</button></div>:<><p role="status">Loading the full architecture guide…</p><div className="skeleton-line"/><div className="skeleton-line"/><div className="skeleton-panel"/></>}</div>;}
