import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Building2, CornerDownLeft, Search, X } from 'lucide-react';
import { concepts, conceptPath, href, industries, industryPath, loadSearchIndex, type SearchEntry } from '../lib/catalog';
import { navigate } from '../lib/state';
import { domainLabel, pad } from './primitives';
export default function SearchDialog({onClose}:{onClose:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [query,setQuery]=useState('');const [active,setActive]=useState(0);const [index,setIndex]=useState<SearchEntry[]>([]);const [status,setStatus]=useState('loading');
  useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.showModal();document.body.style.overflow='hidden';let live=true;loadSearchIndex().then(items=>{if(live){setIndex(items);setStatus('ready');}}).catch(()=>{if(live)setStatus('limited');});return()=>{live=false;dialog.current?.close();document.body.style.overflow='';previous?.focus();};},[]);
  const results=useMemo(()=>{const q=query.toLowerCase().trim();const terms=q.split(/\s+/).filter(Boolean);const map=new Map(index.map(i=>[`${i.type}/${i.key}`,i.text]));const entries=[...concepts.map(c=>({key:`concept/${c.id}`,title:c.title,description:c.summary,label:`${pad(c.id)} · ${domainLabel(c.category)}`,path:conceptPath(c),fallback:`${c.id} ${c.title} ${c.summary} ${c.keywords.join(' ')} ${c.componentNames.join(' ')} ${c.industry}`.toLowerCase(),industry:false})),...industries.map(i=>({key:`industry/${i.slug}`,title:i.title,description:i.summary,label:i.name,path:industryPath(i),fallback:`${i.name} ${i.title} ${i.summary}`.toLowerCase(),industry:true}))];return q?entries.filter(item=>terms.every(word=>`${item.fallback} ${map.get(item.key)||''}`.includes(word))).sort((a,b)=>Number(b.title.toLowerCase().includes(q))-Number(a.title.toLowerCase().includes(q))):entries.filter(item=>['concept/1','concept/21','concept/41','concept/62','industry/banking'].includes(item.key));},[index,query]);
  const shown=results.slice(0,12);const open=(path:string)=>{onClose();navigate(path);};
  return <dialog ref={dialog} className="search-dialog" aria-label="Search architecture reference" onCancel={onClose} onClick={e=>{if(e.target===dialog.current){const r=dialog.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="search-dialog-input"><Search size={22}/><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setActive(0);}} aria-label="Search the entire reference" placeholder="Concept, component, use case, or industry…" onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(n=>Math.min(n+1,Math.max(0,shown.length-1)));}if(e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(n-1,0));}if(e.key==='Enter'&&shown[active])open(shown[active].path);}}/><button className="icon-button" aria-label="Close search" onClick={onClose}><X size={19}/></button></div><div className="search-dialog-label">{query?`${results.length} MATCHING RESULTS${results.length>12?' · SHOWING FIRST 12':''}`:'START WITH A CONNECTION'}<span>{status==='ready'?'FULL-TEXT SEARCH':status==='loading'?'LOADING FULL INDEX':'SUMMARY SEARCH'}</span></div><div className="search-results">{shown.map((item,i)=><a href={href(item.path)} key={item.key} className={active===i?'active':''} onClick={e=>{e.preventDefault();open(item.path);}} onMouseEnter={()=>setActive(i)}><span className="search-result-symbol">{item.industry?<Building2 size={19}/>:item.label.split(' · ')[0]}</span><div><small>{item.label}</small><strong>{item.title}</strong><p>{item.description}</p></div><ArrowUpRight size={17}/></a>)}{!shown.length&&<div className="search-empty"><Search size={25}/><h3>No connections found.</h3><p>Try “authorization”, “memory”, “manufacturing”, or a concept number.</p></div>}</div><div className="search-dialog-footer"><span><kbd>↑</kbd><kbd>↓</kbd> navigate</span><span><CornerDownLeft size={13}/> open result</span><span><kbd>esc</kbd> close</span></div></dialog>;
}
