import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Bookmark, Check, Grid2X2, List, Search, SlidersHorizontal, Workflow, X } from 'lucide-react';
import { domains } from '../data/domains';
import { concepts, conceptPath, href, industries, loadSearchIndex, type SearchEntry } from '../lib/catalog';
import type { Progress } from '../lib/state';
import { ConceptCard, domainColor, domainLabel, EmptyState, IndustryCard, MiniNetwork, PageIntro, pad } from '../ui/primitives';

export default function CatalogPage({mode='concepts',domain,progress,onSave}:{mode?:'concepts'|'advanced'|'saved'|'diagrams';domain?:number;progress:Progress;onSave:(id:number)=>void}){
  const [query,setQuery]=useState('');const [category,setCategory]=useState(domain??-1);const [sort,setSort]=useState('number');const [view,setView]=useState('grid');const [limit,setLimit]=useState(18);const [level,setLevel]=useState('all');const [index,setIndex]=useState<SearchEntry[]>([]);const [searchStatus,setSearchStatus]=useState('loading');
  useEffect(()=>{let active=true;loadSearchIndex().then(data=>{if(active){setIndex(data);setSearchStatus('ready');}}).catch(()=>{if(active)setSearchStatus('limited');});return()=>{active=false;};},[]);
  const levelOf=(id:number)=>id>100?'advanced':(id-1)%20<5?'foundation':(id-1)%20<13?'intermediate':'advanced';
  const filtered=useMemo(()=>{const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);const byKey=new Map(index.filter(i=>i.type==='concept').map(i=>[i.key,i.text]));return concepts.filter(c=>(mode==='advanced'?c.id>100:mode==='saved'?progress.saved.includes(c.id):mode==='diagrams'?true:c.id<=100)&&(category===-1||c.category===category)&&(level==='all'||levelOf(c.id)===level)&&words.every(word=>(byKey.get(String(c.id))||`${c.title} ${c.summary} ${c.keywords.join(' ')} ${c.componentNames.join(' ')} ${c.industry}`.toLowerCase()).includes(word))).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='category'?a.category-b.category||a.id-b.id:sort==='reading'?a.words-b.words:a.id-b.id);},[category,index,level,mode,progress.saved,query,sort]);
  const categoryInfo=domain===undefined?undefined:domains[domain];const intro=categoryInfo?{eyebrow:`DOMAIN ${pad(domain!+1)} · CONCEPTS ${categoryInfo.range}`,title:categoryInfo.title,description:categoryInfo.description}:mode==='advanced'?{eyebrow:'BEYOND THE ORIGINAL 100',title:'The next layer of agent architecture.',description:'Twelve additional concepts for protocol boundaries, evaluation, durable execution, and operational control. The original curriculum stays intact.'}:mode==='saved'?{eyebrow:'YOUR PERSONAL REFERENCE',title:'Keep your best connections close.',description:'Saved concepts stay in this browser. Build a collection for your next design review.'}:mode==='diagrams'?{eyebrow:'MAKE THE ARCHITECTURE VISIBLE',title:'A library of connected ideas.',description:'Explore topic-specific Mermaid diagrams. Open a concept to inspect, zoom, copy, or download its architecture.'}:{eyebrow:'THE CANONICAL COLLECTION',title:'100 concepts. A complete design vocabulary.',description:'Search the architecture, components, use cases, and tradeoffs. Build understanding one connection at a time.'};
  return <><PageIntro {...intro}/>{categoryInfo&&<div className={`domain-principles color-${categoryInfo.color}`}><div><Workflow size={23}/><h2>{categoryInfo.question}</h2></div><ul>{categoryInfo.principles.map(text=><li key={text}><Check size={15}/>{text}</li>)}</ul></div>}
    <div className="catalog-controls"><div className="catalog-search"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setLimit(18);}} placeholder="Search concepts, components, or use cases…" aria-label="Search concepts"/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="Clear search"><X size={16}/></button>}<kbd>/</kbd></div>
    {domain===undefined&&mode!=='advanced'&&<div className="category-tabs" role="group" aria-label="Filter by domain"><button className={category===-1?'active':''} onClick={()=>{setCategory(-1);setLimit(18);}}>All domains</button>{domains.map(d=><button key={d.id} className={category===d.id?'active':''} onClick={()=>{setCategory(d.id);setLimit(18);}}>{d.short}</button>)}{mode==='diagrams'&&<button className={category===5?'active':''} onClick={()=>setCategory(5)}>Advanced</button>}</div>}
    <div className="catalog-toolbar"><span><strong>{filtered.length}</strong> {mode==='diagrams'?'diagram guides':'concepts'}{categoryInfo?` in this domain`:''}</span><div><label><SlidersHorizontal size={14}/><span className="sr-only">Difficulty</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All levels</option><option value="foundation">Foundation</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label><span className="sr-only">Sort concepts</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="number">Curriculum order</option><option value="title">Title A–Z</option><option value="category">Category</option><option value="reading">Reading time</option></select></label><div className="view-switch"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><Grid2X2 size={16}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={16}/></button></div></div></div>{query&&searchStatus!=='ready'&&<p className="small-note" role="status">{searchStatus==='loading'?'Loading full-text search; titles and summaries are already searchable.':'Full-text search is unavailable. Titles, summaries, components, and keywords remain searchable.'}</p>}</div>
    {!filtered.length?<EmptyState title={mode==='saved'&&!progress.saved.length?'Your collection starts with one idea.':'No concepts match this search.'} text={mode==='saved'?'Save any concept using its bookmark button.':'Try a different phrase or clear your filters.'} action={mode==='saved'?<a href={href('concepts/')} className="button primary">Explore concepts<ArrowRight size={16}/></a>:<button className="button secondary" onClick={()=>{setQuery('');setCategory(domain??-1);setLevel('all');}}>Clear filters</button>}/>:view==='grid'?<div className={mode==='diagrams'?'diagram-library-grid':'concept-grid'}>{filtered.slice(0,limit).map(c=>mode==='diagrams'?<a className={`diagram-library-card color-${domainColor(c.category)}`} key={c.id} href={href(conceptPath(c))}><div><span>CONCEPT {pad(c.id)}</span><ArrowUpRight size={16}/></div><MiniNetwork variant={c.category}/><h3>{c.title}</h3><p>{c.summary}</p><span><Workflow size={14}/>{c.diagrams} Mermaid {c.diagrams===1?'diagram':'diagrams'}</span></a>:<ConceptCard key={c.id} concept={c} progress={progress} onSave={onSave}/>)}</div>:<div className="concept-list">{filtered.slice(0,limit).map(c=><article key={c.id}><span className="list-number">{pad(c.id)}</span><a href={href(conceptPath(c))}><h3>{c.title}</h3><p>{c.summary}</p><small>{domainLabel(c.category)}</small></a><button className="icon-button" onClick={()=>onSave(c.id)} aria-label={`${progress.saved.includes(c.id)?'Unsave':'Save'} ${c.title}`}><Bookmark size={17} fill={progress.saved.includes(c.id)?'currentColor':'none'}/></button><a className="icon-button" href={href(conceptPath(c))} aria-label={`Read ${c.title}`}><ArrowUpRight size={18}/></a></article>)}</div>}
    {filtered.length>limit&&<div className="load-more"><span>Showing {Math.min(limit,filtered.length)} of {filtered.length}</span><button className="button secondary" onClick={()=>setLimit(l=>l+18)}>Load more concepts<ArrowDown size={16}/></button><button className="text-link" onClick={()=>setLimit(filtered.length)}>Show all</button></div>}
  </>;
}
export function IndustriesPage(){const [query,setQuery]=useState('');const [sector,setSector]=useState('all');const sectors=[...new Set(industries.map(i=>i.sector))];const filtered=industries.filter(i=>(sector==='all'||i.sector===sector)&&`${i.name} ${i.title} ${i.summary}`.toLowerCase().includes(query.toLowerCase()));return <><PageIntro eyebrow="AGENTS IN THE REAL WORLD" title="An architecture for every kind of challenge." description={`Explore ${industries.length} industry blueprints with specialist agents, enterprise systems, diagrams, failure paths, and operational measures. Each is an illustrative design you can adapt.`}/><div className="industry-library-callout"><NetworkMark/><div><h2>Different industries. Explicit boundaries.</h2><p>Every blueprint defines what each agent can observe, recommend, and execute—and where a person retains the decision.</p></div><a href={href('studio/')} className="button secondary">Compare in the studio<ArrowRight size={15}/></a></div><div className="industry-filters"><div className="catalog-search"><Search size={18}/><input aria-label="Search industries" placeholder="Search an industry or business problem…" value={query} onChange={e=>setQuery(e.target.value)}/></div><label><span className="sr-only">Industry sector</span><select value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All sectors</option>{sectors.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="results-line">{filtered.length} industry {filtered.length===1?'blueprint':'blueprints'}</div>{filtered.length?<div className="industry-grid">{filtered.map((i,n)=><IndustryCard key={i.slug} industry={i} index={n}/>)}</div>:<EmptyState title="No industry found." text="Try another business problem or clear the sector filter." action={<button className="button secondary" onClick={()=>{setQuery('');setSector('all');}}>Clear filters</button>}/>}</>;}
function NetworkMark(){return <span className="large-feature-icon"><Workflow size={28}/></span>;}
