import { ArrowLeft, ArrowRight, Bookmark, Check, Clock3, Code2, FileText, Layers3, Workflow } from 'lucide-react';
import { domains } from '../data/domains';
import source from '../data/source.json';
import { conceptById, conceptPath, href, type ConceptSummary } from '../lib/catalog';
import type { Concept } from '../lib/content-types';
import type { Progress } from '../lib/state';
import { useResource } from '../lib/useResource';
import MermaidDiagram from '../ui/MermaidDiagram';
import { ArchitectureChecklist, FailureCards, References, ReferenceSection, ResourceLoading, RuntimeFlow, TableOfContents, TradeoffTable } from '../ui/ReferenceParts';
import { Breadcrumb, domainColor, domainLabel, pad } from '../ui/primitives';

const toc=[{id:'overview',label:'Overview'},{id:'production',label:'Why it matters'},{id:'components',label:'Components'},{id:'architecture',label:'Architecture diagrams'},{id:'runtime',label:'Runtime flow'},{id:'use-case',label:'Industry use case'},{id:'tradeoffs',label:'Tradeoffs'},{id:'failures',label:'Failure scenarios'},{id:'mistakes',label:'Common mistakes'},{id:'when-to-use',label:'When to use / avoid'},{id:'checklist',label:'Architecture checklist'},{id:'related',label:'Related concepts'},{id:'references',label:'Primary references'}];
export default function ConceptPage({summary,progress,onSave,onComplete}:{summary:ConceptSummary;progress:Progress;onSave:(id:number)=>void;onComplete:(id:number)=>void}){
  const {data:concept,error,retry}=useResource<Concept>('concepts',summary.slug);
  if(!concept)return <ResourceLoading title={summary.title} error={error} retry={retry}/>;
  const domain=domains[concept.category];const done=progress.completed.includes(concept.id);const saved=progress.saved.includes(concept.id);
  const previous=concept.id>1&&concept.id!==101?conceptById(concept.id-1):undefined;const next=concept.id!==100?conceptById(concept.id+1):undefined;
  const original=source.find(c=>c.id===concept.id);
  return <div className={`lesson-page color-${domainColor(concept.category)}`} id="page-top">
    <Breadcrumb items={[{label:concept.id>100?'Advanced collection':'Concepts',path:concept.id>100?'advanced/':'concepts/'},{label:concept.title}]}/>
    <header className="lesson-header"><div className="lesson-eyebrow"><a href={href(domain?.slug?`${domain.slug}/`:'advanced/')}><Layers3 size={14}/>{domainLabel(concept.category)}</a><span>{concept.id>100?'EXTENSION':'CONCEPT'} {pad(concept.id)}</span></div><h1><span>{pad(concept.id)}<span className="title-dash"> — </span></span>{concept.title}</h1><p>{concept.summary}</p><div className="lesson-meta"><span><Clock3 size={14}/>{Math.max(4,Math.ceil(summary.words/190))} min read</span><span><Workflow size={14}/>{concept.diagrams.length} {concept.diagrams.length===1?'diagram':'diagrams'}</span><span><FileText size={14}/>Production reference</span><button className={`button small ${saved?'saved':''}`} onClick={()=>onSave(concept.id)} aria-pressed={saved}><Bookmark size={14} fill={saved?'currentColor':'none'}/>{saved?'Saved':'Save concept'}</button></div></header>
    <div className="reference-layout"><article className="reference-body">
      <ReferenceSection id="overview" kicker="THE ARCHITECTURE DECISION" title="Concept overview">{concept.overview.map((text,i)=><p key={i}>{text}</p>)}{original&&<details className="language-note"><summary>Read the original idea in Hindi</summary><p lang="hi">{original.hindi}</p><small>The expanded English guide provides production nuance. Source terminology has been made vendor-neutral.</small></details>}</ReferenceSection>
      <ReferenceSection id="production" title="Why it matters in production"><div className="maturity-stages">{[['01','Proof of concept',concept.production.poc],['02','Production',concept.production.production],['03','Enterprise scale',concept.production.scale]].map(([n,label,text])=><div key={n}><span>{n}</span><h3>{label}</h3><p>{text}</p></div>)}</div></ReferenceSection>
      <ReferenceSection id="components" title="Architecture components"><div className="component-grid">{concept.components.map((component,i)=><div key={i}><Code2 size={18}/><h3>{component.name}</h3><p>{component.role}</p></div>)}</div></ReferenceSection>
      <ReferenceSection id="architecture" kicker="MAKE THE CONNECTIONS VISIBLE" title="The architecture, mapped">{concept.diagrams.map((diagram,i)=><MermaidDiagram key={i} diagram={diagram}/>)}</ReferenceSection>
      <ReferenceSection id="runtime" title="Runtime flow"><RuntimeFlow steps={concept.flow}/></ReferenceSection>
      <ReferenceSection id="use-case" kicker={concept.useCase.industry.toUpperCase()} title={concept.useCase.title}><div className="use-case-note">Illustrative enterprise scenario · Design considerations, not a reported customer outcome.</div><h3>Business situation</h3><p>{concept.useCase.situation}</p><h3>The problem</h3><p>{concept.useCase.problem}</p><h3>Why an agent is useful</h3><p>{concept.useCase.requirement}</p><h3>Architecture</h3><p>{concept.useCase.architecture}</p><h3>What happens at runtime</h3><ol className="prose-list">{concept.useCase.runtime.map((text,i)=><li key={i}>{text}</li>)}</ol><div className="callout warning"><strong>When something fails</strong><p>{concept.useCase.failure}</p></div><h3>Operational impact</h3><p>{concept.useCase.impact}</p></ReferenceSection>
      <ReferenceSection id="tradeoffs" title="Architecture tradeoffs"><TradeoffTable items={concept.tradeoffs}/></ReferenceSection>
      <ReferenceSection id="failures" title="Failure scenarios & recovery"><FailureCards items={concept.failures}/></ReferenceSection>
      <ReferenceSection id="mistakes" title="Common architecture mistakes"><div className="mistake-list">{concept.mistakes.map((item,i)=><div key={i}><span>{pad(i+1)}</span><div><h3>{item.mistake}</h3><p>{item.fix}</p></div></div>)}</div></ReferenceSection>
      <ReferenceSection id="when-to-use" title="When to choose this pattern"><div className="choice-panels"><div><h3>Choose it when</h3><ul>{concept.whenToUse.map((text,i)=><li key={i}>{text}</li>)}</ul></div><div><h3>Avoid it when</h3><ul>{concept.whenNotToUse.map((text,i)=><li key={i}>{text}</li>)}</ul></div></div></ReferenceSection>
      <ReferenceSection id="checklist" kicker="TAKE IT INTO YOUR DESIGN REVIEW" title="Architecture checklist"><ArchitectureChecklist conceptId={concept.id} items={concept.checklist}/></ReferenceSection>
      <ReferenceSection id="related" title="Connect the next concept"><div className="related-grid">{concept.related.map(id=>{const c=conceptById(id);return c&&<a key={id} href={href(conceptPath(c))}><span>{pad(id)}</span><div><strong>{c.title}</strong><small>{domainLabel(c.category)}</small></div><ArrowRight size={16}/></a>;})}</div></ReferenceSection>
      <ReferenceSection id="references" title="Primary references"><p>Use these sources to verify implementation details and follow the underlying standards, research, or product documentation.</p><References items={concept.references}/></ReferenceSection>
      <div className="lesson-complete"><div><Check size={25}/><div><h3>{done?'A new connection made.':'Ready to connect the next idea?'}</h3><p>{done?'This concept is recorded in your learning progress.':'Mark this concept complete when you can explain the design and its tradeoffs.'}</p></div></div><button className={`button ${done?'secondary':'primary'}`} onClick={()=>onComplete(concept.id)}>{done?'Mark incomplete':'Mark complete'}<Check size={16}/></button></div>
      <nav className="previous-next" aria-label="Sequential concepts">{previous?<a href={href(conceptPath(previous))}><ArrowLeft size={18}/><div><small>PREVIOUS CONCEPT</small><strong>{pad(previous.id)} — {previous.title}</strong></div></a>:<span/>}{next?<a href={href(conceptPath(next))}><div><small>NEXT CONCEPT</small><strong>{pad(next.id)} — {next.title}</strong></div><ArrowRight size={18}/></a>:<a href={href(concept.id===100?'advanced/':'concepts/')}><div><small>KEEP EXPLORING</small><strong>{concept.id===100?'Explore the advanced collection':'Return to all concepts'}</strong></div><ArrowRight size={18}/></a>}</nav>
    </article><TableOfContents items={toc}/></div>
  </div>;
}
