import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Bot, Check, ChevronRight, GitCompareArrows, KeyRound, Pause, Play, RotateCcw, ShieldCheck, TriangleAlert, Workflow } from 'lucide-react';
import { href, industries, industryPath } from '../lib/catalog';
import type { Industry } from '../lib/content-types';
import { useResource } from '../lib/useResource';
import MermaidDiagram from '../ui/MermaidDiagram';
import { FailureCards, ResourceLoading } from '../ui/ReferenceParts';
import { PageIntro, pad } from '../ui/primitives';

export default function StudioPage(){
  const query=new URLSearchParams(location.search).get('industry');
  const [selected,setSelected]=useState(industries.some(i=>i.slug===query)?query!:'banking');
  const [step,setStep]=useState(0);const [agent,setAgent]=useState(0);const [playing,setPlaying]=useState(false);const [mode,setMode]=useState<'runtime'|'failure'|'compare'>('runtime');
  const {data:industry,error,retry}=useResource<Industry>('industries',selected);
  useEffect(()=>{setStep(0);setAgent(0);setPlaying(false);setMode('runtime');},[selected]);
  useEffect(()=>{if(!playing||!industry)return;const timer=setInterval(()=>setStep(current=>{if(current>=industry.flow.length-1){setPlaying(false);return current;}return current+1;}),2300);return()=>clearInterval(timer);},[playing,industry]);
  function choose(slug:string){setSelected(slug);history.replaceState({},'',href(`studio/?industry=${slug}`));}
  return <><PageIntro eyebrow="THE ARCHITECTURE STUDIO" title="Follow the system. Understand the decisions." description="Choose an industry, inspect the agent team, and step through the runtime. An interactive reference walkthrough—no live agents or enterprise systems are connected."/><div className="studio-toolbar"><label>Industry blueprint<select value={selected} onChange={e=>choose(e.target.value)} aria-label="Choose studio industry">{industries.map(i=><option key={i.slug} value={i.slug}>{i.name}</option>)}</select></label><div className="studio-mode" aria-label="Studio view">{([{key:'runtime',label:'Runtime',Icon:Workflow},{key:'failure',label:'Failure paths',Icon:TriangleAlert},{key:'compare',label:'Compare',Icon:GitCompareArrows}] as const).map(v=><button key={v.key} className={mode===v.key?'active':''} onClick={()=>{setMode(v.key);setPlaying(false);}}><v.Icon size={15}/>{v.label}</button>)}</div><button className="icon-button" onClick={()=>{setStep(0);setAgent(0);setPlaying(false);setMode('runtime');}} aria-label="Reset studio"><RotateCcw size={17}/></button></div>
    {!industry?<ResourceLoading title="Loading the blueprint" error={error} retry={retry}/>:mode==='compare'?<Comparison industry={industry}/>:<>
      <div className="studio-title-row"><div><span className="section-label">{industry.name.toUpperCase()} · REFERENCE WORKFLOW</span><h2>{industry.title}</h2></div><a className="text-link" href={href(industryPath(industry))}>Read the full blueprint<ArrowRight size={15}/></a></div>
      {mode==='runtime'?<><div className="studio-workbench"><div className="agent-map"><div className="map-label"><span className="status-light"/>BOUNDED AGENT TEAM<span>SELECT AN AGENT</span></div><div className="orchestrator-node"><Workflow size={23}/><div><strong>Workflow orchestrator</strong><span>Coordinates contracts, state, and deadlines</span></div><span className="policy-chip"><ShieldCheck size={13}/>Policy gate</span></div><div className="agent-map-connectors"/><div className="studio-agent-grid">{industry.agents.map((a,i)=><button key={a.name} className={agent===i?'selected':''} aria-pressed={agent===i} onClick={()=>setAgent(i)}><Bot size={24}/><span>AGENT {pad(i+1)}</span><strong>{a.name}</strong><span className="inspect-agent">Inspect role<ChevronRight size={12}/></span></button>)}</div><div className="map-decision-boundary"><KeyRound size={15}/><span>Tools enforce permissions. People own consequential decisions.</span></div></div><aside className="agent-inspector"><span className="section-label">INSPECT THE RESPONSIBILITY</span><h3>{industry.agents[agent].name}</h3><p>{industry.agents[agent].responsibility}</p><h4>Connected tools</h4><div className="agent-tools">{industry.agents[agent].tools.map(tool=><span key={tool}>{tool}</span>)}</div><div className="inspector-boundary"><KeyRound size={18}/><strong>Authority boundary</strong><p>{industry.agents[agent].boundary}</p></div></aside></div>
      <div className="walkthrough"><div className="walkthrough-top"><span><span className="section-label">RUNTIME WALKTHROUGH</span><strong>Step {step+1} of {industry.flow.length}</strong></span><button className="button small primary" onClick={()=>{if(step===industry.flow.length-1)setStep(0);setPlaying(!playing);}}>{playing?<Pause size={14}/>:<Play size={14}/>} {playing?'Pause':'Play walkthrough'}</button></div><div className="walkthrough-rail">{industry.flow.map((flow,i)=><button key={i} className={`${step===i?'active':''} ${step>i?'passed':''}`} onClick={()=>{setStep(i);setPlaying(false);}} aria-label={`Step ${i+1}: ${flow.title}`} aria-current={step===i?'step':undefined}><span>{step>i?<Check size={12}/>:pad(i+1)}</span><strong>{flow.title}</strong></button>)}</div><div className="walkthrough-detail" aria-live="polite"><span>{pad(step+1)}</span><div><h3>{industry.flow[step].title}</h3><p>{industry.flow[step].description}</p></div><div><button className="icon-button" disabled={step===0} onClick={()=>{setStep(s=>s-1);setPlaying(false);}} aria-label="Previous runtime step"><ArrowLeft size={17}/></button><button className="icon-button" disabled={step===industry.flow.length-1} onClick={()=>{setStep(s=>s+1);setPlaying(false);}} aria-label="Next runtime step"><ArrowRight size={17}/></button></div></div></div>
      <MermaidDiagram diagram={industry.diagrams[0]}/></>:<div className="studio-failures"><div className="callout warning"><TriangleAlert size={24}/><div><h3>Explore the recovery design</h3><p>These are documented failure scenarios. No live system is being fault-injected.</p></div></div><FailureCards items={industry.failures}/>{industry.diagrams.slice(1).map((diagram,i)=><MermaidDiagram key={i} diagram={diagram}/>)}</div>}
    </>}
  </>;
}
function Comparison({industry}:{industry:Industry}){const [other,setOther]=useState(industries.find(i=>i.slug!==industry.slug)?.slug||industry.slug);const {data,error,retry}=useResource<Industry>('industries',other);return <div className="studio-comparison"><label className="comparison-select">Compare {industry.name} with<select value={other} onChange={e=>setOther(e.target.value)} aria-label="Compare with industry">{industries.filter(i=>i.slug!==industry.slug).map(i=><option key={i.slug} value={i.slug}>{i.name}</option>)}</select></label>{!data?<ResourceLoading title="Loading comparison" error={error} retry={retry}/>:<div className="comparison-columns">{[industry,data].map(i=><article key={i.slug}><span className="section-label">{i.name}</span><h2>{i.title}</h2><p>{i.summary}</p><h3>Agent responsibilities</h3><ul>{i.agents.map(a=><li key={a.name}><strong>{a.name}</strong><p>{a.responsibility}</p></li>)}</ul><h3>Key control boundaries</h3><ul>{i.controls.slice(0,3).map(control=><li key={control}>{control}</li>)}</ul><h3>What to measure</h3><div className="agent-tools">{i.metrics.map(m=><span key={m.name}>{m.name}</span>)}</div><a className="button secondary" href={href(industryPath(i))}>Open full architecture<ArrowRight size={15}/></a></article>)}</div>}</div>;}
