import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const binary = process.env.BROWSE_BIN || 'browse';
const base = process.env.QA_BASE_URL || 'http://localhost:5173/ai-agent-architecture-concepts';
const reports = [];
const browse = (...args) => execFileSync(binary, args, { env: process.env, encoding: 'utf8', timeout: 45000 }).trim();
const check = (name, expression) => {
  const result = browse('js', `JSON.stringify({passed: Boolean(${expression})})`);
  if (!result.includes('"passed":true')) throw new Error(`${name}: ${result}`);
  reports.push({ name, passed: true });
  console.log(`PASS ${name}`);
};
const visit = path => { browse('goto', `${base}/#/${path}`); browse('wait', '#main-content'); };
const click = selector => browse('click', selector);
const fill = (selector, value) => browse('fill', selector, value);
const screenshot = name => browse('screenshot', '--viewport', resolve(`artifacts/${name}.png`));

mkdirSync('artifacts', { recursive: true });
const source = JSON.parse(readFileSync('src/data/source.json', 'utf8'));
const md = readFileSync('Anaplan_AI_Architect_Top_100_Topics.md', 'utf8');
if (source.length !== 100 || source.some((t, i) => t.id !== i + 1 || !md.includes(t.title) || !md.includes(t.hindi))) throw new Error('Source curriculum integrity failed');
console.log('PASS All 100 source titles and Hindi explanations preserved');
reports.push({ name: 'All 100 source titles and Hindi explanations preserved', passed: true });
const notes = readFileSync('src/data/topics.ts', 'utf8').match(/const notes = `([\s\S]*?)`\.trim/)[1].trim().split('\n');
if (notes.length !== 100 || notes.some(row => row.split('|').length !== 4 || row.split('|')[1].split('>').length !== 4) || new Set(notes.map(row => row.split('|')[1])).size !== 100) throw new Error('Topic guide completeness failed');
reports.push({ name: 'Every topic has a unique four-stage diagram, explanation, tradeoff, and interview question', passed: true });
console.log('PASS Every topic has a complete guide and unique diagram');

visit('overview');
browse('console', '--clear');
// The test runs against this local preview only and resets its local learning data.
browse('js', "localStorage.removeItem('atlas-progress'); localStorage.setItem('atlas-theme','light')");
browse('reload');
browse('viewport', '1440x1000');
browse('wait', '.hero');
check('Overview has five domain entry points', "document.querySelectorAll('.domain-card').length === 5");
check('Desktop has no horizontal overflow', 'document.documentElement.scrollWidth <= innerWidth');
click('[aria-label="Explore Research agent"]');
check('Hero diagram selects the specialist step', "document.querySelector('.hero-diagram-footer').textContent.includes('Bring in the specialists')");
click('[aria-label="Explore User request"]');
screenshot('overview-desktop');

click('.hero-buttons .primary');
browse('wait', '.catalog-grid');
check('All 100 topics are available', "document.querySelector('.results-label').textContent.includes('100') && document.querySelectorAll('.topic-card').length === 12");
fill('[aria-label="Search topics"]', 'HyDE');
check('Search finds the matching concept', "document.querySelectorAll('.topic-card').length === 1 && document.querySelector('.topic-card h3').textContent.includes('HyDE')");
fill('[aria-label="Search topics"]', 'no-such-concept-xyz');
check('No-result state is useful', "document.querySelector('.empty-state h3').textContent === 'No concepts found'");
click('.empty-state .button');
click('.category-tabs button:nth-child(3)');
check('Security domain filter returns 20 topics', "document.querySelector('.results-label').textContent.includes('20') && document.querySelector('.topic-card h3').textContent === 'Authorization-Aware RAG'");
browse('select', '.level-select select', 'Advanced');
check('Difficulty filter returns seven advanced security topics', "document.querySelectorAll('.topic-card').length === 7");
browse('select', '.level-select select', 'all');
click('.load-more .button');
check('Load more exposes remaining domain topics', "document.querySelectorAll('.topic-card').length === 20");
click('[aria-label="List view"]');
check('List view preserves filtered results', "document.querySelectorAll('.topic-list-row').length === 20");

visit('topic/1');
browse('wait', '.lesson');
check('Lesson includes bilingual explanations and a four-stage diagram', "document.querySelectorAll('.flow-step').length === 4 && document.querySelector('.hindi-note[lang=hi]') !== null");
check('Hindi font is bundled and loaded', "[...document.fonts].some(font => font.family === 'Noto Sans Devanagari' && font.status === 'loaded')");
click('.lesson-metadata button');
check('Bookmark saved', "JSON.parse(localStorage.getItem('atlas-progress')).saved.includes(1)");
click('.flow-step-wrap:nth-child(3) .flow-step');
check('Diagram step click updates the explainer', "document.querySelector('.flow-explainer strong').textContent === 'Specialist agents'");
click('[aria-label="Reset diagram"]');
check('Diagram reset returns to step one', "document.querySelector('.flow-explainer strong').textContent === 'User request'");
click('.knowledge-check .button');
check('Interview answer reveals topic-specific guidance', "document.querySelector('.answer-reveal').textContent.includes('Extra agents add coordination cost')");
click('.lesson-completion .button');
check('Completion persisted', "JSON.parse(localStorage.getItem('atlas-progress')).completed.includes(1)");
browse('reload');
browse('wait', '.lesson-completion');
check('Completion and bookmark survive reload', "document.querySelector('.lesson-completion h3').textContent === 'One more connection made.' && document.querySelector('.lesson-metadata button').textContent.includes('Saved')");
click('[aria-label="Show Hindi explanations"]');
check('Hindi toggle changes the lesson explanation language', "document.querySelector('.lesson-intro').lang === 'hi'");
click('[aria-label="Show English explanations"]');
screenshot('lesson-desktop');

visit('saved');
check('Saved collection contains the bookmarked topic', "document.querySelectorAll('.topic-card').length === 1 && document.querySelector('.topic-card h3').textContent === 'Multi-Agent Orchestration'");
visit('progress');
check('Progress dashboard reflects actual completion', "document.querySelectorAll('.completed-row').length === 1 && document.querySelector('.progress-stat-main').textContent.includes('1')");
visit('path');
click('.path-choice:nth-child(2)');
check('Learning path selection changes the roadmap', "document.querySelector('.path-section-title h2').textContent === 'The production mindset' && document.querySelectorAll('.roadmap-item').length === 10");
visit('diagrams');
check('Diagram library has unique topic flows', "document.querySelectorAll('.mini-topic-flow').length === 12 && document.querySelectorAll('.mini-step').length === 48");
visit('practice');
click('.practice-reveal .button');
check('Practice reveals answer guidance', "document.querySelector('.practice-answer').textContent.includes('The tradeoff.')");
click('.practice-answer-buttons .primary');
check('Practice advances and records self-assessment', "JSON.parse(localStorage.getItem('atlas-progress')).practiced.includes(1) && document.querySelector('.practice-concept').textContent.includes('Concept 02')");

browse('press', 'Control+k');
browse('wait', '.search-modal[open]');
fill('[aria-label="Search all 100 topics"]', 'Hybrid Search');
browse('press', 'Enter');
browse('wait', '.lesson');
check('Keyboard search navigates to the selected concept', "document.querySelector('.lesson-header h1').textContent === 'Hybrid Search (Dense + Sparse)'");
click('[aria-label="Use dark theme"]');
check('Dark theme enabled', "document.documentElement.dataset.theme === 'dark'");
check('Dark theme paints the main canvas and readable text', "getComputedStyle(document.body).backgroundColor === 'rgb(25, 34, 28)' && getComputedStyle(document.body).color === 'rgb(226, 232, 219)'");
browse('reload');
check('Theme preference persists', "document.documentElement.dataset.theme === 'dark'");
screenshot('lesson-dark');
click('[aria-label="Use light theme"]');

browse('viewport', '390x844');
visit('overview');
check('Mobile overview has no horizontal overflow', 'document.documentElement.scrollWidth <= innerWidth');
check('Hidden mobile navigation cannot receive keyboard focus', "document.querySelector('.sidebar').inert");
click('[aria-label="Open navigation"]');
check('Mobile navigation opens', "document.querySelector('.sidebar').classList.contains('is-open')");
check('Open navigation makes the page behind it inactive', "document.querySelector('.main-shell').inert");
click('.sidebar a[href="#/topics"]');
browse('wait', '.catalog-grid');
check('Mobile navigation closes after selection', "!document.querySelector('.sidebar').classList.contains('is-open') && document.querySelector('.catalog-grid') !== null");
check('Mobile catalog has no horizontal overflow', 'document.documentElement.scrollWidth <= innerWidth');
visit('topic/62');
check('Mobile lesson has no horizontal overflow', 'document.documentElement.scrollWidth <= innerWidth');
screenshot('lesson-mobile');
visit('overview');
screenshot('overview-mobile');
browse('viewport', '768x1024');
check('Tablet overview has no horizontal overflow', 'document.documentElement.scrollWidth <= innerWidth');
browse('viewport', '1440x1000');
visit('overview');
const errors = browse('console', '--errors');
writeFileSync('artifacts/qa-report.json', JSON.stringify({ url: base, generatedAt: new Date().toISOString(), checks: reports, browserErrors: errors }, null, 2));
console.log(`\n${reports.length} checks passed. Browser errors:\n${errors}`);
// Leave a clean preview instead of the test's study activity.
browse('js', "localStorage.removeItem('atlas-progress')");
browse('reload');
screenshot('overview-desktop');
