import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
const binary=process.env.BROWSE_BIN||'browse';
const base=(process.env.QA_BASE_URL||'http://localhost:4175/ai-agent-architecture-concepts').replace(/\/$/,'');
const reports=[];
const browse=(...args)=>execFileSync(binary,args,{env:process.env,encoding:'utf8',timeout:60000}).trim();
const js=code=>browse('js',code);
const check=(name,expression)=>{let result='';for(let attempt=0;attempt<12;attempt++){result=js(`JSON.stringify({passed:Boolean(${expression})})`);if(result.includes('"passed":true'))break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,150);}if(!result.includes('"passed":true'))throw new Error(`${name}: ${result}`);reports.push({name,passed:true});console.log(`PASS ${name}`);};
const visit=(path='')=>{browse('goto',`${base}/${path}`);browse('wait','#main-content');};
const click=selector=>browse('click',selector);
const fill=(selector,value)=>browse('fill',selector,value);
const screenshot=name=>browse('screenshot','--viewport',resolve(`artifacts/${name}.png`));
const catalog=JSON.parse(readFileSync('src/data/catalog.json','utf8'));
const cpath=id=>`concepts/${catalog.concepts.find(c=>c.id===id).slug}/`;
mkdirSync('artifacts',{recursive:true});
visit();
// This runner uses a disposable local browser profile and resets only this origin's learning state.
js("localStorage.removeItem('atlas-progress');localStorage.removeItem('architecture-checklist-1');localStorage.setItem('atlas-theme','light')");
browse('reload');browse('viewport','1440x1000');browse('console','--clear');
check('Welcome has the required website heading',"document.querySelector('h1').textContent.replace(/\\s+/g,' ').includes('Top 100 AI Agent') && document.querySelector('h1').textContent.includes('Design Concepts')");
check('Welcome contains all five domain entry points',"document.querySelectorAll('.welcome-domain').length===5");
check('Welcome fits desktop viewport','document.documentElement.scrollWidth<=innerWidth');
click('.industry-switch button:nth-child(2)');
check('Welcome industry switch changes agent architecture',"document.querySelector('.welcome-diagram').textContent.includes('Maintenance planner')");
click('.complete-index>button');
check('Welcome expands to all100 canonical links',"document.querySelectorAll('.compact-index a').length===100");
click('.complete-index>button');click('.industry-switch button:first-child');screenshot('v2-welcome-desktop');
visit('concepts/');
check('Canonical catalog has100 concepts',"document.querySelector('.catalog-toolbar').textContent.includes('100')&&document.querySelectorAll('.concept-card').length===18");
fill('[aria-label="Search concepts"]','HyDE');
check('Search finds a specialized concept',"document.querySelectorAll('.concept-card').length===1&&document.querySelector('.concept-card h3').textContent.includes('HyDE')");
fill('[aria-label="Search concepts"]','no-result-xyz-zzz');
check('Empty search has a recovery action',"document.querySelector('.empty-state').textContent.includes('Clear filters')");
click('.empty-state .button');
click('.category-tabs button:nth-child(3)');
check('Domain filtering returns20 canonical concepts',"document.querySelector('.catalog-toolbar').textContent.includes('20')");
browse('select','.catalog-toolbar label:first-child select','advanced');
check('Difficulty filter applies to the selected domain',"document.querySelectorAll('.concept-card').length===7");
click('[aria-label="List view"]');
check('List view keeps filtered results',"document.querySelectorAll('.concept-list article').length===7");
browse('select','.catalog-toolbar label:first-child select','all');
click('.category-tabs button:first-child');
click('[aria-label="Grid view"]');
click('.load-more .text-link');
check('All100 catalog entries can be displayed',"document.querySelectorAll('.concept-card').length===100");
fill('[aria-label="Search concepts"]',catalog.concepts.find(c=>c.id===1).componentNames[0]);
check('Search indexes architecture components',"[...document.querySelectorAll('.concept-card h3')].some(e=>e.textContent==='Multi-Agent Orchestration')");
visit('security-governance/');
check('Dedicated domain URL lists its20 concepts',"document.querySelector('h1').textContent.includes('Security')&&document.querySelector('.catalog-toolbar').textContent.includes('20')");
visit('advanced/');
check('Extensions remain separate from the canonical100',"document.querySelectorAll('.concept-card').length===12&&document.querySelector('.catalog-toolbar').textContent.includes('12')");
visit(cpath(1));browse('wait','.lesson-header');
check('Every required concept section is rendered',"document.querySelectorAll('.reference-section').length===13&&document.querySelectorAll('.page-toc nav a').length===13");
check('Concept page has a real canonical URL',"document.querySelector('link[rel=canonical]').href.endsWith('/concepts/multi-agent-orchestration/')");
check('Concept includes use-case and recovery content',"document.querySelector('#use-case').textContent.includes('Business situation')&&document.querySelectorAll('#failures .failure-cards article').length>=2");
check('Related concepts link semantically across domains',"document.querySelectorAll('#related a').length>=4");
click('.lesson-meta button');
check('Bookmark persists in browser storage',"JSON.parse(localStorage.getItem('atlas-progress')).saved.includes(1)");
click('.architecture-checklist label:first-of-type');
check('Architecture checklist persists a reviewed item',"JSON.parse(localStorage.getItem('architecture-checklist-1')).includes(0)");
click('.lesson-complete button');
check('Completion persists in browser storage',"JSON.parse(localStorage.getItem('atlas-progress')).completed.includes(1)");
browse('reload');browse('wait','.lesson-header');
check('Completion and checklist survive reload',"document.querySelector('.lesson-complete button').textContent.includes('Mark incomplete')&&document.querySelector('.architecture-checklist input').checked");
click('.page-toc a[href="#architecture"]');
browse('wait','#architecture .mermaid-figure:first-of-type.is-rendered');
check('Mermaid diagram is rendered as accessibleSVG',"document.querySelector('#architecture .diagram-svg svg[aria-labelledby]')!==null");
click('#architecture .mermaid-figure:first-of-type [aria-label="Show Mermaid source"]');
check('Mermaid source is inspectable',"document.querySelector('#architecture .diagram-source').textContent.includes('flowchart')");
click('#architecture .mermaid-figure:first-of-type [aria-label="Show Mermaid source"]');
click('#architecture .mermaid-figure:first-of-type [aria-label="Zoom in"]');
check('Diagram zoom works',"document.querySelector('#architecture .zoom-controls').textContent.includes('125%')");
click('#architecture .mermaid-figure:first-of-type [aria-label="Reset zoom"]');
check('Diagram zoom resets',"document.querySelector('#architecture .zoom-controls').textContent.includes('100%')");
screenshot('v2-diagram-desktop');
click('.page-toc a[href="#runtime"]');
check('Table of contents reaches the runtime section',"location.hash==='#runtime'&&document.querySelector('#runtime').getBoundingClientRect().top<180");
visit('saved/');
check('Saved library contains the selected concept',"document.querySelectorAll('.concept-card').length===1&&document.querySelector('.concept-card h3').textContent==='Multi-Agent Orchestration'");
visit('progress/');
check('Progress dashboard reflects actual completion',"document.querySelectorAll('.completed-list a').length===1");
visit('learning-paths/');
click('.path-choices button:nth-child(2)');
check('Learning path selection updates the roadmap',"document.querySelector('.path-detail-heading h2').textContent==='Take a system into production'&&document.querySelectorAll('.path-roadmap>a').length===10");
visit('practice/');browse('wait','.practice-card');
click('.practice-card>.button');
check('Interview practice reveals substantive talking points',"document.querySelector('.practice-answer').textContent.includes('The failure path.')");
click('.practice-buttons .primary');
check('Practice records self-assessment and advances',"JSON.parse(localStorage.getItem('atlas-progress')).practiced.includes(1)");
visit('industries/');
check('Industry library contains all28 blueprints',"document.querySelectorAll('.industry-card').length===28");
fill('[aria-label="Search industries"]','maritime');
check('Industry search filters the library',"document.querySelectorAll('.industry-card').length===1&&document.querySelector('.industry-card').textContent.toLowerCase().includes('maritime')");
visit('industries/banking/');browse('wait','.agent-team');
check('Industry blueprint defines specialist authority',"document.querySelectorAll('.agent-team article').length>=4&&document.querySelectorAll('.authority-boundary').length>=4");
check('Industry blueprint includes systems controls metrics and rollout',"document.querySelectorAll('#systems .component-grid>div').length>=3&&document.querySelectorAll('#metrics .metrics-grid>div').length>=4&&document.querySelectorAll('.rollout-plan li').length===3");
visit('studio/?industry=banking');browse('wait','.studio-workbench');
click('.studio-agent-grid button:nth-child(2)');
check('Studio agent inspection updates the responsibility panel',"document.querySelector('.agent-inspector h3').textContent===document.querySelector('.studio-agent-grid button:nth-child(2) strong').textContent");
click('[aria-label="Next runtime step"]');
check('Studio runtime controls advance the walkthrough',"document.querySelector('.walkthrough-top strong').textContent.includes('Step 2')");
click('.studio-mode button:nth-child(2)');
check('Studio exposes documented failure paths',"document.querySelector('.studio-failures')!==null&&document.querySelectorAll('.failure-cards article').length>=2");
click('.studio-mode button:nth-child(3)');browse('wait','.comparison-columns');
check('Studio compares distinct industry architectures',"document.querySelectorAll('.comparison-columns>article').length===2");
browse('select','[aria-label="Choose studio industry"]','manufacturing');browse('wait','.studio-workbench');
check('Industry selection updates the studio URL and workflow',"location.search.includes('manufacturing')&&document.querySelector('.studio-title-row').textContent.includes('MANUFACTURING')");
screenshot('v2-studio-desktop');
browse('press','Control+k');browse('wait','.search-dialog[open]');
fill('[aria-label="Search the entire reference"]','Hybrid Search');browse('press','Enter');browse('wait','.lesson-header');
check('Keyboard search opens a canonical concept page',"document.querySelector('.lesson-header h1').textContent.includes('Hybrid Search')&&location.pathname.includes('hybrid-search')");
check('SPA navigation updates all SEO metadata',"document.querySelector('meta[name="+'"twitter:title"'+"]').content.includes('Hybrid Search')&&document.querySelector('script[type="+'"application/ld+json"'+"]').textContent.includes('Hybrid Search')");
click('[aria-label="Use dark theme"]');
check('Dark theme is applied',"document.documentElement.dataset.theme==='dark'");
browse('reload');browse('wait','.lesson-header');
check('Dark theme survives reload',"document.documentElement.dataset.theme==='dark'");
click('.page-toc a[href="#architecture"]');browse('wait','#architecture .mermaid-figure:first-of-type.is-rendered');
check('Mermaid renders in dark theme',"document.querySelector('#architecture .diagram-svg svg')!==null&&document.querySelectorAll('.diagram-error').length===0");
screenshot('v2-diagram-dark');
click('[aria-label="Use light theme"]');
browse('viewport','390x844');visit();
check('Mobile welcome fits the viewport','document.documentElement.scrollWidth<=innerWidth');
check('Hidden mobile navigation is inactive',"document.querySelector('.sidebar').inert");
click('[aria-label="Open navigation"]');
check('Mobile navigation opens and inactivates background',"document.querySelector('.sidebar').classList.contains('open')&&document.querySelector('.site-shell').inert");
click('.sidebar a[href="/ai-agent-architecture-concepts/concepts/"]');
check('Mobile navigation follows links and closes',"!document.querySelector('.sidebar').classList.contains('open')&&document.querySelector('.catalog-controls')!==null");
for(const path of ['', 'concepts/','industries/','studio/','learning-paths/','practice/','progress/',cpath(1),cpath(100),cpath(112),'industries/maritime/']){
 visit(path);
 if(path==='studio/')browse('wait','.studio-workbench');
 if(path==='practice/')browse('wait','.practice-card');
 check(`Mobile layout has no horizontal overflow: ${path||'welcome'}`,'document.documentElement.scrollWidth<=innerWidth');
}
visit();screenshot('v2-welcome-mobile');visit(cpath(1));screenshot('v2-concept-mobile');
browse('viewport','320x740');visit();check('Narrow320px welcome fits the viewport','document.documentElement.scrollWidth<=innerWidth');visit('studio/');browse('wait','.studio-workbench');check('Narrow320px studio fits the viewport','document.documentElement.scrollWidth<=innerWidth');
browse('viewport','768x1024');visit();check('Tablet welcome fits the viewport','document.documentElement.scrollWidth<=innerWidth');
browse('viewport','1440x1000');
visit('#/topic/1');browse('wait','.lesson-header');
check('Legacy shared topic links resolve to canonical paths',"location.pathname.endsWith('/concepts/multi-agent-orchestration/')&&!location.hash.startsWith('#/')");
visit('#/__proto__');browse('reload');
check('Unknown legacy keys do not crash navigation',"document.querySelector('h1').textContent.includes('Top 100 AI Agent')");
js("history.pushState({},'', '/ai-agent-architecture-concepts/__proto__/');window.dispatchEvent(new PopStateEvent('popstate'))");
check('Unknown paths show a recoverable page',"document.querySelector('.empty-state').textContent.includes('This path has not been mapped.')&&document.querySelector('meta[name=robots]').content==='noindex'");
click('.empty-state .button');
check('Unknown page recovery restores catalog metadata',"document.querySelector('.catalog-controls')!==null&&!document.querySelector('meta[name=robots]')");
const errors=browse('console','--errors');
if(!errors.includes('(no console errors)'))throw new Error(errors);
reports.push({name:'No browser console errors',passed:true});
writeFileSync('artifacts/qa-report.json',JSON.stringify({url:base,generatedAt:new Date().toISOString(),checks:reports,browserErrors:errors},null,2));
console.log(`${reports.length} browser checks passed. No console errors.`);
js("localStorage.removeItem('atlas-progress');localStorage.removeItem('architecture-checklist-1')");visit();
